<?php

foreach ($this->listcategory as $category)
{
    if (isset($this->list[$category['id']])){
        echo '<h4>' . $category['scaption'] . '</h4>';
        foreach ($this->list[$category['id']] as $val){
            $data_item = null;
            if (!empty($val['scaption']) and !empty($val['options']['sdesc'])) {
                $data_item = 'data-container="body" data-toggle="popover"  data-placement="top" data-trigger="hover" data-title="'.$val['scaption'].'" data-content="'.$val['options']['sdesc'].'"';
            }
            echo '<div><a href="javascript:void(0);" data-target="elementvalue" data-value="' . $val['sname'] . '" '.$data_item.'><span>' . $val['sname'] . '</span></a></div>';
        }
    }
}

if (isset($this->list[''])){
    echo '<h4>Другое</h4>';
    foreach ($this->list[''] as $val){
        $data_item = null;
        if (!empty($val['scaption']) and !empty($val['options']['sdesc'])) {
            $data_item = 'data-container="body" data-toggle="popover"  data-placement="top" data-trigger="hover" data-title="'.$val['scaption'].'" data-content="'.$val['options']['sdesc'].'"';
        }
        echo '<div><a href="javascript:void(0);" data-target="elementvalue" data-value="' . $val['sname'] . '" '.$data_item.'><span>' . $val['sname'] . '</span></a></div>';
    }
}
