<style>
.wrap-hoshform_system_auth {
	width: 50%;
	max-width: 500px;
	margin: 0px auto;
	padding: 15px;
	background: #f0f0f0;
	border-radius: 3px;
	border: 1px solid #c6c6c6;
}

@media ( max-width : 768px) {
	.wrap-hoshform_system_auth {
		width: 100%;
		max-width: auto;
		margin: 0px auto;
		padding: 15px;
		background: #f0f0f0;
		border-radius: 3px;
		border: 1px solid #c6c6c6;
	}
}

.act-btn {
	margin-top: 20px;
}
</style>
:element[susername] :element[spassword]
<div class="act-btn">
	<button type="submit" class="btn btn-default">
		:_[HOSH_SYS_AUTH_ENTER] <i class="fa fa-angle-right"></i>
	</button>
</div>