:helper[Layout_Default]
<div class="top-level">
	<div class="row">
	<div class="col-xs-7">:helper[Title]</div>
	<div class="col-xs-5">
	   <div class="action-btn pull-right">
	       :helper[Layout_BtnAction]	       
	   </div>
	</div>
	</div>
</div>
    :helper[Layout_AlertObject]	
	<div class="options-level">
		<div class="row">
	       <div class="col-sm-8">:element[scaption]</div>
	       <div class="col-sm-4">:element[sname]</div>
	   </div>
	</div>

<div class="menu-nav" >
    <div class="menu-nav-container">
	<div class="pull-left">
		<ul class="nav nav-tabs">
			<li><a href="#elements" title=":_[SYS_FORM_ELEMENTS]"><i class="fa fa-list"></i><span class="hidden-xs">:_[SYS_FORM_ELEMENTS]</span></a></li>
			<li><a href="#settings" title=":_[SYS_FORM_SETTINGS]"><i class="fa fa-cog"></i><span class="hidden-xs">:_[SYS_FORM_SETTINGS]</span></a></li>
			<li><a href="#acl" title=":_[SYS_FORM_ACL]"><i class="fa fa-unlock-alt"></i><span class="hidden-xs">:_[SYS_FORM_ACL]</span></a></li>
		</ul>		
	</div>	
	<div class="pull-right action-nav"><button title=":_[SYS_SAVE]" class="btn btn-primary"><span class="hidden-sm"><i class="fa fa-floppy-o"></i></span><span class="hidden-xs">:_[SYS_SAVE]</span></button></div>
	<div style="clear:both"></div>
	</div>
</div>

<div>
	<div id="elements">
		<div class="page-header">
			<h2><i class="fa fa-list"></i>&nbsp; :_[SYS_FORM_ELEMENTS]</h2>
		</div>
		<div class="element-group">
		:helper[ListElements]
		</div>
	</div>
	
	<div id="settings">
		<div class="page-header"><h2><i class="fa fa-cog"></i>&nbsp; :_[SYS_FORM_SETTINGS]</h2></div>
		<div class="element-group">				
		:element[translate_helper]
		:elementhelper[translate_helper]
		<hr />		
		:element[idstate]		
		</div>
	</div>
	
	<div id="acl">
		<div class="page-header"><h2><i class="fa fa-unlock-alt"></i>&nbsp; :_[SYS_FORM_ACL]</h2></div>
		<div class="element-group">	
		:element[bpublic]					
		</div>
	</div>	
</div>