:helper[Layout_Default]
<div class="top-level">
	<h3>:helper[Title]</h3>
</div>
<div class="bghead-level">

	<div class="row">
		<div class="col-md-8">:element[label]</div>
		<div class="col-md-4">:element[sname]</div>
		<div class="col-md-8">:element[decorator_helper]
                              :elementhelper[decorator_helper]
        </div>
		<div class="col-md-4">:element[norder]</div>
	</div>

</div>

<div class="footer-level">
	<div class="action-btn">
		<button type="button" class="btn btn-primary" data-task="saveform"><i class="fa fa-floppy-o"></i>&nbsp; :_[SYS_SAVE]</button>
		<button type="button" class="btn btn-default" data-task="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i>&nbsp; :_[SYS_CLOSE]</button>
	</div>
</div>