:helper[Layout_Default]
<div class="top-level">
<h3>:helper[Title]</h3>
</div>
<div class="bghead-level">

	<div class="row">
		<div class="col-md-6">:element[type]</div>
		<div class="col-md-6">:element[name]</div>
		<div class="col-md-6">:element[options_label]</div>
		<div class="col-md-6">:element[bpublic]</div>
	</div>

</div>
<div class="footer-level">
	<div class="action-btn">
		<button type="button" class="btn btn-primary" data-task="saveform"><i class="fa fa-floppy-o"></i>&nbsp; :_[SYS_SAVE]</button>
		<button type="button" class="btn btn-default" data-task="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i>&nbsp; :_[SYS_CANCEL]</button>
	</div>
</div>