<?php
$task_icon = array(
        'delete' => '<i class="fa fa-trash-o fa-fw"></i>',
        'default' => '<i class="fa fa-task fa-fw"></i>'
);

$hoshtranslate = Hosh_Translate::getInstance();
$hoshtranslate->load('form/_');
$translate = $hoshtranslate->getAdapter();
foreach ($this->list as $val) :
    $classitem = null;
    if ($val['id'] === $this->idactive) {
        $classitem .= ' active';
    }
    $classitem .= ' ' . strtolower($val['snamestate']);
    ?>
<li class="leftmenu-item<?php echo $classitem;?>">

<?php if (isset($val['task'])):?>

<div class="row sm">
		<div class="col-xs-10 colsm">
			<a href="<?php echo $val['href']?>"
				title="<?php echo $val['scaption']?>"><?php echo $val['scaption']?></a>
		</div>
		<div class="col-xs-2 colsm">

			<div class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i
					class="fa fa-ellipsis-v"></i></a>
				<ul class="dropdown-menu dropdown-menu-right">
<?php foreach($val['task'] as $key=>$task):

if (empty($task['icon'])){
    $task['icon'] = (isset($task_icon[$key])) ? $task_icon[$key] : $task_icon['default'];
}

?>
<li><a href="#" data-task="action_object"
						data-action="<?php echo $key;?>"
						data-target="<?php echo $val['id']?>"><?php echo $task['icon'];?> <?php echo $task['scaption'];?></a></li>
<?php endforeach;?>
</ul>
			</div>

		</div>
	</div>
<?php else:?>
<a href="<?php echo $val['href']?>"
	title="<?php echo $val['scaption']?>"><?php echo $val['scaption']?></a>
<?php endif;?>
</li>
<?php endforeach;?>